@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEwLCJlbWFpbCI6ImJyZW5kYTk0OTMxM0BnbWFpbC5jb20iLCJpYXQiOjE3NTIwMjEwNTIsImV4cCI6MTc1MjAyODI1Mn0.b80TCClHiaQtyATZUhkfcB6kvwuBARRjb5dgzWWZ6uU

### Compra de varios juegos (carrito)
POST http://localhost:5000/ventas/comprar HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "juegos": [
    { "juegoId": 29, "cantidad": 2 },
    { "juegoId": 36, "cantidad": 1 }
  ]
}
