POST http://localhost:5000/auth/registrar
Content-Type: application/json

{
  "email": "brenda949313@gmail.com",
  "password": "123456",
  "username": "usuarioPrueba"
}

### Verificar código recibido
POST http://localhost:5000/auth/verificar
Content-Type: application/json

{
  "email": "brenda949313@gmail.com",
  "codigo": "732626"
}

### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "prueba2@email.com",
  "password": "123456"
}



### Crear admin
POST http://localhost:5000/auth/registrar
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123",
  "username": "Admin",
  "rol": "admin"
}

### Verificar código
POST http://localhost:5000/auth/verificar
Content-Type: application/json

{
  "email": "admin@admin.com",
  "codigo": "779673",
  "rol": "admin"
}