### Obtener todos los juegos
GET http://localhost:5000/juegos HTTP/1.1

### Agregar un nuevo juego
POST http://localhost:5000/juegos HTTP/1.1
Content-Type: application/json

{
  "nombre": "Nuevo Juego",
  "descripcion": "Juego de prueba",
  "categoria": "RPG",
  "plataforma": "Nintendo",
  "precio": 49.99,
  "descuento": 5,
  "oferta": true,
  "ventas": 0,
  "valoracion": 0,
  "imagen": "nuevo_juego.jpg",
  "trailer": "trailer.mp4"
}


### Editar un juego por ID
PUT http://localhost:5000/juegos/1 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Nuevo Juego",
  "descripcion": "Juego de prueba",
  "categoria": "RPG",
  "plataforma": "Nintendo",
  "precio": 49.99,
  "descuento": 5,
  "oferta": true,
  "ventas": 0,
  "valoracion": 0,
  "imagen": "nuevo_juego.jpg",
  "trailer": "trailer.mp4"
}

### Eliminar un juego por ID
DELETE http://localhost:5000/juegos/3 HTTP/1.1
