@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOjEwLCJlbWFpbCI6ImJyZW5kYTk0OTMxM0BnbWFpbC5jb20iLCJpYXQiOjE3NTIxMDk0MTEsImV4cCI6MTc1MjExNjYxMX0.PdIVbOER2jpHk1EIld3HmeBtDzI_wz-DRSiynlNIM34

### Obtener todos los juegos
GET http://localhost:5000/juegos HTTP/1.1

### Obtener juego por id
GET http://localhost:5000/juegos/41 HTTP/1.1

### Agregar un nuevo juego
POST http://localhost:5000/juegos HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Nuevo Juego",
  "descripcion": "Juego de prueba",
  "precio": 49.99,
  "descuento": 5,
  "oferta": true,
  "ventas": 0,
  "valoracion": 0,
  "imagen": "nuevo_juego.jpg",
  "trailer": "trailer.mp4",
  "categoria": "RPG",
  "plataforma": "PC",
  "imagenes": [
    "https://cdn1.com/image1.jpg",
    "https://cdn1.com/image2.jpg"
  ]
}

### Editar un juego por ID
PUT http://localhost:5000/juegos/41 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "CyberQuest Reloaded",
  "descripcion": "Actualización con nuevos niveles",
  "categoria": "RPG",
  "plataforma": "Nintendo",
  "precio": 49.99,
  "descuento": 5,
  "oferta": true,
  "ventas": 200,
  "valoracion": 4.7,
  "imagen": "nuevo.jpg",
  "trailer": "nuevo_trailer.mp4",
  "imagenes": [
    "https://cdn1.com/image1edit.jpg"
  ]
}

### Eliminar un juego por ID
DELETE http://localhost:5000/juegos/11 HTTP/1.1
Authorization: Bearer {{token}}

### Buscar juegos por nombre 
GET http://localhost:5000/juegos/search?nombre=Cy HTTP/1.1

### Filtrar juegos por fecha
GET http://localhost:5000/juegos/filtrar?fecha=2027-07-01 HTTP/1.1

### Filtrar juegos por categoría 
GET http://localhost:5000/juegos/filtrar?categoria=Aventura HTTP/1.1

### Filtrar juegos por plataforma 
GET http://localhost:5000/juegos/filtrar?plataforma=PlayStation HTTP/1.1

### Filtrar juegos mediante rago de precio
GET http://localhost:5000/juegos/filtrar?precioMin=20&precioMax=60 HTTP/1.1

###Obtener categorias juegos
GET http://localhost:5000/juegos/categorias HTTP/1.1


###Obtener plataformas juegos
GET http://localhost:5000/juegos/plataformas HTTP/1.1
